# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\GTM_SDC_specific_MTL.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_specific_MTL_window(object):
    def setupUi(self, specific_MTL_window):
        specific_MTL_window.setObjectName("specific_MTL_window")
        specific_MTL_window.resize(855, 600)
        self.centralwidget = QtWidgets.QWidget(specific_MTL_window)
        self.centralwidget.setObjectName("centralwidget")
        self.Generate_specific_MTL = QtWidgets.QPushButton(self.centralwidget)
        self.Generate_specific_MTL.setGeometry(QtCore.QRect(310, 510, 241, 41))
        self.Generate_specific_MTL.setObjectName("Generate_specific_MTL")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 831, 491))
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 811, 461))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rowTemplateWidget = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.rowTemplateWidget.setObjectName("rowTemplateWidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.rowTemplateWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 805, 51))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.gridLayoutWidget)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.gridLayout.addWidget(self.dateTimeEdit_2, 1, 3, 1, 1)
        self.Sunlit_power_on = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.Sunlit_power_on.setObjectName("Sunlit_power_on")
        self.gridLayout.addWidget(self.Sunlit_power_on, 1, 7, 1, 1)
        self.add_row = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.add_row.setEnabled(True)
        self.add_row.setObjectName("add_row")
        self.gridLayout.addWidget(self.add_row, 1, 9, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.SAA_power_on = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.SAA_power_on.setObjectName("SAA_power_on")
        self.gridLayout.addWidget(self.SAA_power_on, 1, 4, 1, 1)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.gridLayoutWidget)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout.addWidget(self.dateTimeEdit, 1, 2, 1, 1)
        self.remove_row = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.remove_row.setObjectName("remove_row")
        self.gridLayout.addWidget(self.remove_row, 1, 10, 1, 1)
        self.polar_region_power_on = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.polar_region_power_on.setObjectName("polar_region_power_on")
        self.gridLayout.addWidget(self.polar_region_power_on, 1, 6, 1, 1)
        self.CMD_config = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.CMD_config.setObjectName("CMD_config")
        self.gridLayout.addWidget(self.CMD_config, 1, 8, 1, 1)
        self.use_timming = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.use_timming.setObjectName("use_timming")
        self.gridLayout.addWidget(self.use_timming, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.rowTemplateWidget)
        specific_MTL_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(specific_MTL_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 855, 22))
        self.menubar.setObjectName("menubar")
        specific_MTL_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(specific_MTL_window)
        self.statusbar.setObjectName("statusbar")
        specific_MTL_window.setStatusBar(self.statusbar)

        self.retranslateUi(specific_MTL_window)
        QtCore.QMetaObject.connectSlotsByName(specific_MTL_window)

    def retranslateUi(self, specific_MTL_window):
        _translate = QtCore.QCoreApplication.translate
        specific_MTL_window.setWindowTitle(_translate("specific_MTL_window", "MainWindow"))
        self.Generate_specific_MTL.setText(_translate("specific_MTL_window", "Generate"))
        self.groupBox.setTitle(_translate("specific_MTL_window", "MTL "))
        self.Sunlit_power_on.setText(_translate("specific_MTL_window", "Sunlit"))
        self.add_row.setText(_translate("specific_MTL_window", "+"))
        self.label.setText(_translate("specific_MTL_window", "1."))
        self.SAA_power_on.setText(_translate("specific_MTL_window", "SAA"))
        self.remove_row.setText(_translate("specific_MTL_window", "-"))
        self.polar_region_power_on.setText(_translate("specific_MTL_window", "polar_region"))
        self.CMD_config.setText(_translate("specific_MTL_window", "CMD_config"))
        self.use_timming.setText(_translate("specific_MTL_window", "on/off time"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    specific_MTL_window = QtWidgets.QMainWindow()
    ui = Ui_specific_MTL_window()
    ui.setupUi(specific_MTL_window)
    specific_MTL_window.show()
    sys.exit(app.exec_())
